__title__ = "duologsync"
__description__ = "Ingest + sync logs from the Duo Admin API into another system."
__url__ = "https://github.com/duosecurity/duo_log_sync"
__version__ = "0.1.0"
__author__ = "Duo Security, Inc."
__license__ = "Apache 2.0"
__email__ = "support@duosecurity.com"
